# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Cryptological Mathematics Exercises
author: Dan Douglas
#logo: images/logo.png
exclude_patterns: [_build, .venv, src, css, tests, requirements.txt, .git, .gitignore, README.md, .DS_Store, "**.ipynb_checkpoints"]
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath

sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    myst_enable_extensions:
      - colon_fence
      - dollarmath

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: cryptomath-book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - markdown/references.bib

# Information about where the book exists on the web
#repository:
#  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
#  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  extra_css:
    - crypto-book.css
  extra_js:
    - sidebar-toggle.js

#  use_issues_button: true
#  use_repository_button: true
